// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSYPDMN9pxL65js5KfCpzvxV2roBJ6ydM',
    appId: '1:921679506173:web:a47c611513ea3f2ad9ec94',
    messagingSenderId: '921679506173',
    projectId: 'fci-app-new-92a6f',
    authDomain: 'fci-app-new-92a6f.firebaseapp.com',
    storageBucket: 'fci-app-new-92a6f.firebasestorage.app',
    measurementId: 'G-3G4EEFY3KK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpVvlqXfQjggPvfvSrVbVYUu6GP2QOpTk',
    appId: '1:921679506173:android:fc315e1b78c17688d9ec94',
    messagingSenderId: '921679506173',
    projectId: 'fci-app-new-92a6f',
    storageBucket: 'fci-app-new-92a6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeXqarOTyuThWnjQ_zcdoe_R45TocrGAs',
    appId: '1:921679506173:ios:e8fcc06896a03ea1d9ec94',
    messagingSenderId: '921679506173',
    projectId: 'fci-app-new-92a6f',
    storageBucket: 'fci-app-new-92a6f.firebasestorage.app',
    iosBundleId: 'com.example.fciAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeXqarOTyuThWnjQ_zcdoe_R45TocrGAs',
    appId: '1:921679506173:ios:e8fcc06896a03ea1d9ec94',
    messagingSenderId: '921679506173',
    projectId: 'fci-app-new-92a6f',
    storageBucket: 'fci-app-new-92a6f.firebasestorage.app',
    iosBundleId: 'com.example.fciAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSYPDMN9pxL65js5KfCpzvxV2roBJ6ydM',
    appId: '1:921679506173:web:6a1e6c353ef2692fd9ec94',
    messagingSenderId: '921679506173',
    projectId: 'fci-app-new-92a6f',
    authDomain: 'fci-app-new-92a6f.firebaseapp.com',
    storageBucket: 'fci-app-new-92a6f.firebasestorage.app',
    measurementId: 'G-8BDDV8BCKD',
  );

}